### PR TITLE
Made some changes to cleaner NLTK code and presentation

### PR DESCRIPTION
**Pull request by alvations**
- Remove the `clear_output()` for Jupyter when downloading data, use the NLTK non-verbose `quiet=True` parameter instead.
- Also added a warm-up session for people completely new to python, https://github.com/usaarhat/wwc/blob/master/resources/completed-notebooks/pywarmup-session1.md
- And a web-socket / XML / JSON session for much later sesions.

From previous python intro classes, sometimes when there's programmers from other languages, it's hard to understand mind-bending concepts in pythonic code. Especially when it comes to file controls and quirky NLP models loading later on. 

The warmup sessions could be complimentary but i think we can totally skip it unless there's a majority of people in the audience that are totally new. It shouldn't take more than 10mins the warmup. Or they can also be a optional "pre-class homework" that people go through, hahahaa...

### CODE REVIEW

**Comment by interrogator** [comment]
re: clear_output() etc., good move, no problems there.

The warmup looks cool! I'm not totally sure how to integrate it into the main lesson plan, especially for the upcoming set of lessons. Some of it looks like it can replace stuff in session 1 though. The file itself can probably get converted to `.ipynb` and given as a link to students who want some more introductory material after the first session. (We should avoid 'pre-class' anything, because it's important that the sessions have a low entry threshold, and that everyone meets one another at the same time.)

@chozelinek, What are your thoughts on all this? Can merge after we hear from you, I think!

**Comment by interrogator** [comment]
Also, your first code cell prints `Hello Word`. I like that.

**Comment by chozelinek** [comment]
If the initial idea of the warmup is to get people trying stuff at home, I think we can tell people to try that for the next session (2). It fits pretty well, since there is a week gap between sessions 1 and 2. Overlap is not bad, it will sound familiar to those who will be present on Friday. It's kind of scaffolding. Learning/teaching is the art of repetition, like acting ;-) It's kind of homework. It's kind of challenge for those who want more.

So, I agree with Daniel. Let's start together, holding hands. And then let them fly later! The idea of this additional materials is very good, indeed.

**Comment by chozelinek** [comment]
By the way, I find webdata very interesting!

**Comment by interrogator** [comment]
Alright, yes, let's give this to people as a thing to do between the first and second sessions.

Also, if list slicing isn't covered in the core sessions, let's put a cell or two from the warmup in there, eh? I can do this tomorrow.

**Comment by interrogator** [comment]
Whoops, wrong button. Silly me.

**Comment by alvations** [comment]
@chozelinek , @interrogator Alright, i'll leave the merging and planning of the warmup code to you guys. If it doesn't fit anywhere in the main sessions, I think we can just leave all the pywarmups for "additional" materials that people can try anytime =)

@chozelinek Yeah, it's nice but it's not my own material, it's Dr Chunk's. I learnt a lot from his webdata lessons. For now, it's just cut and paste from my exercises but i think we can easily introduce some `BeautifulSoup`, simple `XML` (without `lxml` yet) and easy `JSON` get and fetching. That way, people can make use of readily available APIs. There's quite a few from http://www.opener-project.eu/webservices/ and http://proycon.github.io/clam/

**Comment by chozelinek** [comment]
@alvations cool stuff! I will check all that. Thinking of a (very) advanced session on web services!

**Pull request merged**
