### PR TITLE
Patches to warmup code, session 2 and new evaluation+list session

### PR DESCRIPTION
**Pull request by alvations**
- Added more verbose information about the 1st warmup code and also adds the link to try.jupyter.com
 - Updated the `urlopen` code in session 2
 - Added a new session draft for later sessions for next year (on list, try-excepts, precision, recall, f-score)

### CODE REVIEW

**Comment by interrogator** [comment]
Looks great! Yes, switching to `requests` is a great idea.

In 25e2268d6cd392fc0937cdb67fd94e3fadae88fd, there must be a clever alternative to all those try statements, thought I can't think of one of the top of my head :)

**Comment by alvations** [comment]
Yeah, Jon Sharpe gave me a brilliant solution to that, we'll cover that much later so I'll add new code and more structured instructions much later.

**Comment by interrogator** [comment]
I really want to know!

**Comment by alvations** [comment]
A hacky approach:

```python
def try_except(func, *params):
    try:
        return func(*params)
    except ZeroDivisionError as e:
        return 0

division = lambda numerator, denominator: numerator / float(denominator)
precision = try_except(division, *(true_pos, (true_pos+false_pos)))
recall = try_except(division, *((true_pos + true_neg), float(len(gold))))
fscore = try_except(division, *( 2*precision*recall, (precision + recall)))
```

Jon Sharpe's answer is a little cleaner: http://stackoverflow.com/a/33689848/610569

**Comment by interrogator** [comment]
What about a [context manager style solution](http://stackoverflow.com/a/27374815)? Could be a bit cleaner...

**Comment by alvations** [comment]
Setting a default and suppressing it looks good too.

**Pull request merged**
